name: build-geo

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build ru_geo.rsc
        run: |
          curl -s https://www.ipdeny.com/ipblocks/data/countries/ru.zone \
          | sed 's/^/\/ip firewall address-list add list=geo_ru address=/' \
          > ru_geo.rsc

      - name: Commit file
        run: |
          git config user.name "geo-bot"
          git config user.email "bot@example.com"
          git add ru_geo.rsc
          git commit -m "update geo list" || exit 0
          git push
