name: build-geo

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build ru_geo.rsc
        run: |
          curl -s https://www.ipdeny.com/ipblocks/data/aggregated/bn-aggregated.zone \
          | sed 's/^/\/ip firewall address-list add list=geo_ru address=/' \
          > ru_geo.rsc

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: update geo list
